In [2]:
import dash
import chardet
from pathlib import Path
from dash import Dash, html, dash_table, dcc
from dash.dependencies import Input, Output
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objs as go

In [4]:
# Read the CSV file
# df = pd.read_csv("./data/IIB Data Breaches - LATEST.xlsx")
df = pd.read_excel("./data/IIB Data Breaches - LATEST.xlsx", engine='openpyxl')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   organisation       488 non-null    object
 1   alternative name   152 non-null    object
 2   records lost       488 non-null    object
 3   year               488 non-null    int64
 4   date               488 non-null    object
 5   story              482 non-null    object
 6   sector             488 non-null    object
 7   method             488 non-null    object
 8   interesting story  98 non-null     object
 9   data sensitivity   487 non-null    float64
 10  displayed records  82 non-null     object
 11  Unnamed: 11        0 non-null      float64
 12  source name        488 non-null    object
 13  1st source link    487 non-null    object
 14  2nd source link    46 non-null     object
 15  ID                 488 non-null    int64
dtypes: float64(2), int64(2), object(12)
memory usage: 61.1+ KB

In [8]:
df[df.duplicated()==True]

Empty DataFrame
Columns: [organisation, alternative name, records lost, year   , date, story, sector, method, interesting story, data sensitivity, displayed records, Unnamed: 11, source name, 1st source link, 2nd source link, ID]
Index: []

In [9]:
df.isnull().sum()

organisation           0
alternative name     336
records lost           0
year                   0
date                   0
story                  6
sector                 0
method                 0
interesting story    390
data sensitivity       1
displayed records    406
Unnamed: 11          488
source name            0
1st source link        1
2nd source link      442
ID                     0
dtype: int64

In [15]:
print("Amount of missing valus in - ")
for column in df.columns:
    percentage_missing = np.mean(df[column].isna())
    print(f'{column} : {round(percentage_missing*100)}%')

Amount of missing valus in -
organisation : 0%
alternative name : 0%
records lost : 0%
year    : 0%
date : 0%
story : 0%
sector : 0%
method : 0%
interesting story : 0%
data sensitivity : 0%
displayed records : 0%
Unnamed: 11 : 0%
source name : 0%
1st source link : 0%
2nd source link : 0%
ID : 0%

In [16]:
df[df["story"].isnull()]

Empty DataFrame
Columns: [organisation, alternative name, records lost, year   , date, story, sector, method, interesting story, data sensitivity, displayed records, Unnamed: 11, source name, 1st source link, 2nd source link, ID]
Index: []

In [17]:
df = df.drop(columns=['alternative name', 'interesting story','displayed records', 'Unnamed: 11', '2nd source link'])
df.to_excel('./data/IIB Data Breaches - Cleaned.xlsx', index=False)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   organisation      488 non-null    object
 1   records lost      488 non-null    object
 2   year              488 non-null    int64
 3   date              488 non-null    object
 4   story             488 non-null    object
 5   sector            488 non-null    object
 6   method            488 non-null    object
 7   data sensitivity  488 non-null    object
 8   source name       488 non-null    object
 9   1st source link   488 non-null    object
 10  ID                488 non-null    int64
dtypes: int64(2), object(9)
memory usage: 42.1+ KB

In [19]:
df[df["data sensitivity"].isnull()]

Empty DataFrame
Columns: [organisation, records lost, year   , date, story, sector, method, data sensitivity, source name, 1st source link, ID]
Index: []

In [20]:
df[df["1st source link"].isnull()]

Empty DataFrame
Columns: [organisation, records lost, year   , date, story, sector, method, data sensitivity, source name, 1st source link, ID]
Index: []

In [21]:
df[df["story"].isnull()]

Empty DataFrame
Columns: [organisation, records lost, year   , date, story, sector, method, data sensitivity, source name, 1st source link, ID]
Index: []

In [3]:
df = df.replace(np.nan, "No Value")
df.to_excel('./data/IIB Data Breaches - Cleaned - Ver2.xlsx', index=False)

NameError: name 'df' is not defined

In [4]:
data_breaches_df = pd.read_excel('./data/IIB Data Breaches - Cleaned - Ver2.xlsx', engine='openpyxl')

In [22]:
data_breaches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   organisation       488 non-null    object
 1   alternative name   488 non-null    object
 2   records lost       488 non-null    object
 3   year               488 non-null    int64
 4   date               488 non-null    object
 5   story              488 non-null    object
 6   sector             488 non-null    object
 7   method             488 non-null    object
 8   interesting story  488 non-null    object
 9   data sensitivity   488 non-null    object
 10  displayed records  488 non-null    object
 11  Unnamed: 11        488 non-null    object
 12  source name        488 non-null    object
 13  1st source link    488 non-null    object
 14  2nd source link    488 non-null    object
 15  ID                 488 non-null    int64
dtypes: int64(2), object(14)
memory usage: 61.1+ KB

In [23]:
data_breaches_df.head(5)

,organisation,alternative name,records lost,year,date,story,sector,method,interesting story,data sensitivity,displayed records,Unnamed: 11,source name,1st source link,2nd source link,ID
0,Kaiser Permanente,No Value,13400000,2024,2024-04-26 00:00:00,A leading U.S. healthcare organization transmi...,health,oops!,No Value,3,No Value,No Value,Bleeping Computer,https://restoreprivacy.com/data-breach-at-kais...,No Value,492
1,Ticketmaster,No Value,560000000,2024,2024-06-02 00:00:00,"Hacker group ShinyHunters say it stole names, ...",media,hacked,y,3,560m,No Value,BBC,https://www.bbc.co.uk/news/articles/cw99ql0239wo,No Value,491
2,Stanford University,No Value,27000,2023,2023-05-12 00:00:00,The Akira ransomware group claims to have stol...,academic,hacked,No Value,2,No Value,No Value,Slashdot,https://yro.slashdot.org/story/24/03/13/205322...,No Value,490
3,Cooler Master,No Value,500000,2024,2024-05-19 00:00:00,Threat actor 'Ghostr' hacked the company's Fan...,tech,hacked,No Value,2,No Value,No Value,Bleeping Computer,https://www.bleepingcomputer.com/news/security...,No Value,489
4,Financial Business and Consumer Solutions,FBCS,3200000,2024,2024-02-14 00:00:00,A U.S. debt collection agency reported a breac...,tech,hacked,No Value,2,No Value,No Value,Bleeping Computer,https://www.bleepingcomputer.com/news/security...,No Value,488

In [24]:
data_breaches_df.columns

Index(['organisation', 'alternative name', 'records lost', 'year   ', 'date',
       'story', 'sector', 'method', 'interesting story', 'data sensitivity',
       'displayed records', 'Unnamed: 11', 'source name', '1st source link',
       '2nd source link', 'ID'],
      dtype='object')

In [25]:
# df['year   '] = df['year   '].str.strip()
# df['year   '] = df['year   '].str.replace(r'\t|\n|\r', '', regex=True)

In [26]:
data_breaches_df.columns

Index(['organisation', 'alternative name', 'records lost', 'year', 'date',
       'story', 'sector', 'method', 'interesting story', 'data sensitivity',
       'displayed records', 'Unnamed: 11', 'source name', '1st source link',
       '2nd source link', 'ID'],
      dtype='object')

# Visualization Begin

In [5]:
# Ensure 'records lost' are cleaned and converted to integers
data_breaches_df['records lost'] = data_breaches_df['records lost'].replace(r'[^\d]', '', regex=True).astype(int)
# Ensure that there are no spaces on the end of the values for the "Method"
data_breaches_df['method'] = data_breaches_df['method'].str.rstrip()
# Ensure that there are no spaces on the end of the values for the "Sector"
data_breaches_df['sector'] = data_breaches_df['sector'].str.rstrip()
# Ensure that there are no space on the end of "year" column
data_breaches_df.rename(columns={'year   ': 'year'}, inplace=True)

# Get unique values for dropdown options
years = data_breaches_df['year'].unique()
organisations = data_breaches_df['organisation'].unique()
sectors = data_breaches_df['sector'].unique()
methods = data_breaches_df['method'].unique()

# Initialize the Dash App
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css', './assets/styles.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    
# Visualization for Data Breaches Analysis Dashboard
html.H1("Data Breaches Analysis Dashboard"),
    
html.Div([
        dcc.Dropdown(
            id='analysis-type',
            options=[
                {'label': 'Sector Analysis', 'value': 'sector'},
                {'label': 'Method Analysis', 'value': 'method'},
                {'label': 'Data Sensitivity Analysis', 'value': 'data_sensitivity'},
                {'label': 'Yearly Trends', 'value': 'yearly_trends'},
                {'label': 'Records Lost Analysis', 'value': 'records_lost'},
            ],
            value='sector'
        )
    ], style={'margin-bottom': '20px'}),
    
    html.Div([
        html.Div([
            dcc.Dropdown(
                id='year-filter',
                options=[{'label': year, 'value': year} for year in years],
                multi=True,
                placeholder='Select Year(s)'
            )
        ], style={'width': '24%', 'display': 'inline-block'}),
        
        html.Div([
            dcc.Dropdown(
                id='organisation-filter',
                options=[{'label': organisation, 'value': organisation} for organisation in organisations],
                multi=True,
                placeholder='Select Organisation(s)'
            )
        ], style={'width': '24%', 'display': 'inline-block'}),
        
        html.Div([
            dcc.Dropdown(
                id='sector-filter',
                options=[{'label': sector, 'value': sector} for sector in sectors],
                multi=True,
                placeholder='Select Sector(s)'
            )
        ], style={'width': '24%', 'display': 'inline-block'}),
        
        html.Div([
            dcc.Dropdown(
                id='method-filter',
                options=[{'label': method, 'value': method} for method in methods],
                multi=True,
                placeholder='Select Method(s)'
            )
        ], style={'width': '24%', 'display': 'inline-block'})
    ], style={'display': 'flex', 'justify-content': 'space-between', 'margin-bottom': '20px'}),
    
    html.Div([
        dcc.Graph(id='graph-output')
    ], className='graph-container'),

    # Visualization for Top 5 Organizations
    html.H2("Top 5 Organizations with Most Records Lost"),
    html.Div([
        dcc.Dropdown(
            id='top-5-year-filter',
            options=[{'label': year, 'value': year} for year in years],
            multi=True,
            placeholder='Select Year(s)'
        ),
        dcc.Graph(id='top-5-graph-output')
    ], className='graph-container'),
    
    # New visualization for number of breaches by year for specific sectors
    html.H2("Number of Breaches by Year for Specific Sectors (2020-2024)"),
    html.Div([
        dcc.Graph(id='sectors-year-graph-output')
    ], className='graph-container'),
    
    # New visualization for percentages of most used method
    html.H2("Percentages of most used methods"),
    html.Div([
        dcc.Graph(id='methods-donut-chart-output')
    ], className='graph-container'),
    
])

# Define the callbacks to update the graphs based on the selected analysis type
@app.callback(
    [Output('graph-output', 'figure'), Output('top-5-graph-output', 'figure')],
    [Input('analysis-type', 'value'),
     Input('year-filter', 'value'),
     Input('organisation-filter', 'value'),
     Input('sector-filter', 'value'),
     Input('method-filter', 'value'),
     Input('top-5-year-filter', 'value')]
)
def update_graph(selected_analysis, selected_years, selected_organisations, selected_sectors, selected_methods, selected_top5_years):
    # Filter the DataFrame based on the selected filters
    df = data_breaches_df
    
    # Apply filters if they are not empty or None
    if selected_years:
        df = df[df['year'].isin(selected_years)]
    if selected_organisations:
        df = df[df['organisation'].isin(selected_organisations)]
    if selected_sectors:
        df = df[df['sector'].isin(selected_sectors)]
    if selected_methods:
        df = df[df['method'].isin(selected_methods)]
        
    # Initialize fig to an empty figure
    fig = {}
    
    # Data Visualization
    
    # Visualization for Sector
    if selected_analysis == 'sector':
        sector_counts = df['sector'].value_counts()
        if not sector_counts.empty:
            fig = px.bar(
                x=sector_counts.index, 
                y=sector_counts.values, 
                labels={'x': 'Sector', 'y': 'Number of Breaches'},
                title='Number of Data Breaches per Sector',
                color=sector_counts.index,  # Color bars by sector
                hover_data={'Sector': sector_counts.index, 'Number of Breaches': sector_counts.values}
            )
        else:
            fig = px.bar(title='No data available for the selected filters')
    
    # Visualization for Method
    elif selected_analysis == 'method':
        method_counts = df['method'].value_counts()
        
        # Aggregate sector information for each method
        sector_info = (
            df.groupby('method')['sector']
            .apply(lambda x: ', '.join(x.unique()))
            .reindex(method_counts.index)
        ).reset_index()
        
        if not method_counts.empty:
            fig = px.bar(
                x=method_counts.index, 
                y=method_counts.values, 
                labels={'x': 'Method', 'y': 'Number of Breaches'},
                title='Number of Data Breaches per Method',
                color=method_counts.index,  # Color bars by method
                hover_data={'Method': method_counts.index, 'Number of Breaches': method_counts.values, 'Sector': sector_info['sector']}
            )
        else:
            fig = px.bar(title='No data available for the selected filters')
    
    # Visualization for Data Sensitivity
    elif selected_analysis == 'data_sensitivity':
        sensitivity_counts = df['data sensitivity'].value_counts()
        if not sensitivity_counts.empty:
            fig = px.bar(
                x=sensitivity_counts.index, 
                y=sensitivity_counts.values, 
                labels={'x': 'Data Sensitivity', 'y': 'Number of Breaches'},
                title='Number of Data Breaches by Data Sensitivity',
                color=sensitivity_counts.index,  # Color bars by data sensitivity
                hover_data={'Data Sensitivity': sensitivity_counts.index, 'Number of Breaches': sensitivity_counts.values}
            )
        else:
            fig = px.bar(title='No data available for the selected filters')
    
    # Visualization for Yearly Trends of data breaches
    elif selected_analysis == 'yearly_trends':
        yearly_trends = df['year'].value_counts().sort_index()
        if not yearly_trends.empty:
            fig = px.line(
                x=yearly_trends.index, 
                y=yearly_trends.values, 
                labels={'x': 'Year', 'y': 'Number of Breaches'},
                title='Number of Data Breaches Over the Years'
            )
        else:
            fig = px.line(title='No data available for the selected filters')
    
    # Visualization for Record Lost
    elif selected_analysis == 'records_lost':
        if not df.empty:
            fig = px.histogram(
                df, 
                x='records lost', 
                nbins=20, 
                labels={'x': 'Records Lost', 'y': 'Frequency'},
                title='Distribution of Records Lost in Data Breaches',
                color=df['sector']  # Color bars by sector
            )
        else:
            fig = px.histogram(title='No data available for the selected filters')
    
    # Top 5 organizations graph
    filtered_top5_df = data_breaches_df.copy()
    if selected_top5_years:
        filtered_top5_df = filtered_top5_df[filtered_top5_df['year'].isin(selected_top5_years)]
    top5_records_by_org = filtered_top5_df.groupby('organisation')['records lost'].sum().nlargest(5).reset_index()
    if not top5_records_by_org.empty:
        fig_top5 = px.bar(
            top5_records_by_org, 
            x='organisation', 
            y='records lost',
            labels={'organisation': 'Organization', 'records lost': 'Records Lost'},
            title='Top 5 Organizations with Most Records Lost',
            color='organisation'  # Color bars by organization
        )
    else:
        fig_top5 = px.bar(title='No data available for the selected filters')

    return fig, fig_top5

# Define the callback for the new visualization
@app.callback(
    Output('sectors-year-graph-output', 'figure'),
    Input('top-5-year-filter', 'value')  # Using this input to refresh graph
)
def update_sectors_year_graph(selected_years):
    specific_years = [2020, 2021, 2022, 2023, 2024]
    sectors = ['web', 'government', 'finance', 'health']
    filtered_df = data_breaches_df[(data_breaches_df['sector'].isin(sectors)) & (data_breaches_df['year'].isin(specific_years))]
    
    fig = px.histogram(
        filtered_df,
        x='year',
        color='sector',
        barmode='group',
        labels={'year': 'Year', 'count': 'Number of Breaches', 'sector': 'Sector'},
        title='Number of Breaches by Year for Specific Sectors (2020-2024)'
    )

    return fig


# Define the callback for the new visualization
@app.callback(
    Output('methods-donut-chart-output', 'figure'),
    Input('top-5-year-filter', 'value')  # Using this input to refresh graph
)
def update_methods_donut_chart(selected_years):
    specific_methods = ['hacked', 'poor security', 'lost device', 'oops!', 'inside job']
    filtered_methods_df = data_breaches_df[data_breaches_df['method'].isin(specific_methods)]
    
    # Calculate the counts and percentages of each method:
    method_counts = filtered_methods_df['method'].value_counts().reset_index()
    method_counts.columns = ['method', 'count']
    method_counts['percentage'] = (method_counts['count'] / method_counts['count'].sum() * 100)
    
    fig_donut = px.pie(
        method_counts,
        names='method',
        values='count',
        hole=0.3, # This makes it a donut chart
        labels={'method': 'Method', 'count': 'Count'},
        title='Percentages of Most Used Methods'
    )
    fig_donut.update_traces(textinfo='percent+label')
    
    return fig_donut

if __name__ == '__main__':
    app.run(debug=True, use_reloader=False, jupyter_mode="tab")  # Turn off reloader if inside Jupyter

Dash app running on http://127.0.0.1:8050/